from src.styles import Styles

from PyQt5 import QtCore, QtGui, QtWidgets


class CustomComboBox(QtWidgets.QComboBox):
    popupAboutToBeShown = QtCore.pyqtSignal()

    def showPopup(self):
        self.popupAboutToBeShown.emit()
        super(CustomComboBox, self).showPopup()

    pass


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(597, 132)
        Form.setStyleSheet(Styles.style_label + Styles.style_spinbox + Styles.style_frame + Styles.style_combo_box
                           + Styles.style_nice_button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.pushButton_hard = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_hard.setObjectName("pushButton_3")
        self.pushButton_hard.setMinimumSize(0, 30)
        self.gridLayout_4.addWidget(self.pushButton_hard, 3, 0, 1, 2)
        self.spinBox_hard = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_hard.setObjectName("spinBox_3")
        self.spinBox_hard.setMinimum(1)
        self.spinBox_hard.setMaximum(10)
        self.gridLayout_4.addWidget(self.spinBox_hard, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 2)
        self.comboBox_hard = CustomComboBox(self.frame_3)
        self.comboBox_hard.setObjectName("comboBox_3")
        self.gridLayout_4.addWidget(self.comboBox_hard, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 0, 2, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.spinBox_easy = QtWidgets.QSpinBox(self.frame)
        self.spinBox_easy.setObjectName("spinBox")
        self.spinBox_easy.setMinimum(1)
        self.spinBox_easy.setMaximum(10)
        self.gridLayout_2.addWidget(self.spinBox_easy, 1, 1, 1, 1)
        self.pushButton_easy = QtWidgets.QPushButton(self.frame)
        self.pushButton_easy.setMinimumSize(0, 30)
        self.pushButton_easy.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton_easy, 3, 0, 1, 2)
        self.comboBox_easy = CustomComboBox(self.frame)
        self.comboBox_easy.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox_easy, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_medium = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_medium.setMinimumSize(0, 30)
        self.pushButton_medium.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_medium, 3, 0, 1, 2)
        self.spinBox_medium = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_medium.setObjectName("spinBox_2")
        self.spinBox_medium.setMinimum(1)
        self.spinBox_medium.setMaximum(10)
        self.gridLayout_3.addWidget(self.spinBox_medium, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 2)
        self.comboBox_medium = CustomComboBox(self.frame_2)
        self.comboBox_medium.setObjectName("comboBox_2")
        self.gridLayout_3.addWidget(self.comboBox_medium, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "Потворений"))
        self.pushButton_hard.setText(_translate("Form", "Начать"))
        self.label_5.setText(_translate("Form", "Сложно"))
        self.label_9.setText(_translate("Form", "Выберите словарь"))
        self.label_3.setText(_translate("Form", "Повторений"))
        self.label.setText(_translate("Form", "Легко"))
        self.pushButton_easy.setText(_translate("Form", "Начать"))
        self.label_7.setText(_translate("Form", "Выберите словарь"))
        self.pushButton_medium.setText(_translate("Form", "Начать"))
        self.label_4.setText(_translate("Form", "Повторений"))
        self.label_2.setText(_translate("Form", "Средне"))
        self.label_8.setText(_translate("Form", "Выберите словарь"))
